/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.team8.gui;

/**
 *
 * @author User
 */
public class LessonUI extends javax.swing.JFrame {

    /**
     * Creates new form lesLogin
     */
    public LessonUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtLessonInput = new javax.swing.JButton();
        jButtLessonEdit = new javax.swing.JButton();
        jButtLessonDel = new javax.swing.JButton();
        jButtLessonClass = new javax.swing.JButton();
        jButtBillissue = new javax.swing.JButton();
        jButtPWchange = new javax.swing.JButton();
        jButtExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtLessonInput.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtLessonInput.setText("강좌 등록");
        jButtLessonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtLessonInputActionPerformed(evt);
            }
        });

        jButtLessonEdit.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtLessonEdit.setText("강좌 변경");
        jButtLessonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtLessonEditActionPerformed(evt);
            }
        });

        jButtLessonDel.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtLessonDel.setText("강좌 삭제");
        jButtLessonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtLessonDelActionPerformed(evt);
            }
        });

        jButtLessonClass.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtLessonClass.setText("강의 개설");
        jButtLessonClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtLessonClassActionPerformed(evt);
            }
        });

        jButtBillissue.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtBillissue.setText("수강료 청구서 발급 하기");
        jButtBillissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBillissueActionPerformed(evt);
            }
        });

        jButtPWchange.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtPWchange.setText("암호 변경");
        jButtPWchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtPWchangeActionPerformed(evt);
            }
        });

        jButtExit.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtExit.setText("종료");
        jButtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtExitActionPerformed(evt);
            }
        });

        jButton1.setText("강의 폐지");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtPWchange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButtExit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtLessonInput, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jButtLessonClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtLessonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtBillissue, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jButtLessonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtLessonInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtLessonDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtLessonClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtBillissue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtLessonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtPWchange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtExit))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtPWchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtPWchangeActionPerformed
        //암호 변경 버튼
        changePW a = new changePW(); //changePW 창 호출
        a.setDefaultCloseOperation(changePW.EXIT_ON_CLOSE);
        a.pack();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButtPWchangeActionPerformed

    private void jButtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtExitActionPerformed
        System.exit(0); //프로그램 종료
    }//GEN-LAST:event_jButtExitActionPerformed

    private void jButtBillissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBillissueActionPerformed
        BIillIssueUI call = new BIillIssueUI();
        call.setDefaultCloseOperation(BIillIssueUI.EXIT_ON_CLOSE);
        call.pack();
        call.setLocationRelativeTo(null);
        call.setVisible(true);
    }//GEN-LAST:event_jButtBillissueActionPerformed

    private void jButtLessonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtLessonInputActionPerformed
        //강좌 등록 버튼
        LessonInputUI call = new LessonInputUI(); //새 창 출력
        call.setDefaultCloseOperation(LessonInputUI.EXIT_ON_CLOSE);
        call.pack();
        call.setLocationRelativeTo(null);
        call.setVisible(true);
    }//GEN-LAST:event_jButtLessonInputActionPerformed

    private void jButtLessonClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtLessonClassActionPerformed
        //강의 개설 버튼
        LessonClassUI call = new LessonClassUI(); //새 창 출력
        call.setDefaultCloseOperation(LessonClassUI.EXIT_ON_CLOSE);
        call.pack();
        call.setLocationRelativeTo(null);
        call.setVisible(true);
    }//GEN-LAST:event_jButtLessonClassActionPerformed

    private void jButtLessonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtLessonEditActionPerformed
        //강좌 변경 버튼
        LessonEditUI call = new LessonEditUI(); //새 창 출력
        call.setDefaultCloseOperation(LessonEditUI.EXIT_ON_CLOSE);
        call.pack();
        call.setLocationRelativeTo(null);
        call.setVisible(true);
    }//GEN-LAST:event_jButtLessonEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 강의 폐지 버튼
        DisableLessonUI call = new DisableLessonUI(); //새 창 출력
        call.setDefaultCloseOperation(DisableLessonUI.EXIT_ON_CLOSE);
        call.pack();
        call.setLocationRelativeTo(null);
        call.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtLessonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtLessonDelActionPerformed
        // 강의 삭제 버튼
        LessonDelUI call = new LessonDelUI(); //새 창 출력
        call.setDefaultCloseOperation(LessonDelUI.EXIT_ON_CLOSE);
        call.pack();
        call.setLocationRelativeTo(null);
        call.setVisible(true);
    }//GEN-LAST:event_jButtLessonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtBillissue;
    private javax.swing.JButton jButtExit;
    private javax.swing.JButton jButtLessonClass;
    private javax.swing.JButton jButtLessonDel;
    private javax.swing.JButton jButtLessonEdit;
    private javax.swing.JButton jButtLessonInput;
    private javax.swing.JButton jButtPWchange;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
