/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.team8.gui;

<<<<<<< HEAD
=======
import cse.team8.userwork.SystemLogin;
import java.io.IOException;
import javax.swing.JOptionPane;

>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
/**
 *
 * @author User
 */
public class ProfessorUI extends javax.swing.JFrame {

    /**
     * Creates new form ProLogin
     */
    public ProfessorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtClassStudentList = new javax.swing.JButton();
        jButtGradeInput = new javax.swing.JButton();
        jButtRoll = new javax.swing.JButton();
        jButtPWChange = new javax.swing.JButton();
        jButtExit = new javax.swing.JButton();
<<<<<<< HEAD
=======
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButtRogOut = new javax.swing.JButton();
>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtClassStudentList.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtClassStudentList.setText("강좌 학생 명단 확인");
        jButtClassStudentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtClassStudentListActionPerformed(evt);
            }
        });

        jButtGradeInput.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtGradeInput.setText("성적 입력");
        jButtGradeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtGradeInputActionPerformed(evt);
            }
        });

        jButtRoll.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtRoll.setText(" 출석부 조회");
        jButtRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtRollActionPerformed(evt);
            }
        });

        jButtPWChange.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtPWChange.setText("암호 변경");
        jButtPWChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtPWChangeActionPerformed(evt);
            }
        });

        jButtExit.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtExit.setText("종료");
        jButtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtExitActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
        jButtRogOut.setFont(new java.awt.Font("맑은 고딕 Semilight", 0, 12)); // NOI18N
        jButtRogOut.setText("로그아웃");
        jButtRogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtRogOutActionPerformed(evt);
            }
        });

>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtPWChange)
                .addGap(87, 87, 87)
                .addComponent(jButtExit)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtClassStudentList, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jButtGradeInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtRoll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
=======
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtPWChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtRogOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 101, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtClassStudentList, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jButtGradeInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtRoll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4))
                .addContainerGap())
>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(62, 62, 62)
=======
                .addGap(34, 34, 34)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
                .addComponent(jButtClassStudentList, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtGradeInput)
                .addGap(34, 34, 34)
                .addComponent(jButtRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtExit)
                    .addComponent(jButtPWChange, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtExit)
                    .addComponent(jButtPWChange, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtRogOut))
>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtRollActionPerformed
        RollUI roll = new RollUI();
        roll.setDefaultCloseOperation(RollUI.EXIT_ON_CLOSE);
        roll.pack();
        roll.setLocationRelativeTo(null);
        roll.setVisible(true);
    }//GEN-LAST:event_jButtRollActionPerformed

    private void jButtPWChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtPWChangeActionPerformed
        //암호 변경 버튼
<<<<<<< HEAD
        changePW a = new changePW(); //changePW 창 호출
        a.setDefaultCloseOperation(changePW.EXIT_ON_CLOSE);
=======
        ChangePW a = new ChangePW(); //changePW 창 호출
        a.setDefaultCloseOperation(ChangePW.EXIT_ON_CLOSE);
>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
        a.pack();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jButtPWChangeActionPerformed

    private void jButtClassStudentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtClassStudentListActionPerformed
        ClassStudentListUI classStudentList = new ClassStudentListUI();
        classStudentList.setDefaultCloseOperation(ClassStudentListUI.EXIT_ON_CLOSE);
        classStudentList.pack();
        classStudentList.setLocationRelativeTo(null);
        classStudentList.setVisible(true);
    }//GEN-LAST:event_jButtClassStudentListActionPerformed

    private void jButtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtExitActionPerformed
<<<<<<< HEAD
        System.exit(0); //프로그램 종료
=======
        int select = JOptionPane.showConfirmDialog(null, "프로그램을 종료하시겠습니까?", "Confirm", JOptionPane.OK_CANCEL_OPTION); //확인, 취소 버튼 출력
        if (select == 0) { //확인 버튼 클릭 시        
            System.exit(0); //프로그램 종료
        }
>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
    }//GEN-LAST:event_jButtExitActionPerformed

    private void jButtGradeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtGradeInputActionPerformed
        // 성적 입력 버튼        
        GradeInputUI gradeInput = new GradeInputUI();
        gradeInput.setDefaultCloseOperation(GradeInputUI.EXIT_ON_CLOSE);
        gradeInput.pack();
        gradeInput.setLocationRelativeTo(null);
        gradeInput.setVisible(true);
    }//GEN-LAST:event_jButtGradeInputActionPerformed

<<<<<<< HEAD
=======
    private void jButtRogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtRogOutActionPerformed
        //로그아웃 버튼
        int select = JOptionPane.showConfirmDialog(null, "로그아웃 하시겠습니까?", "Confirm", JOptionPane.OK_CANCEL_OPTION); //확인, 취소 버튼 출력
        if (select == 0) { //확인 버튼 클릭 시
            SystemLogin systemLogin = new SystemLogin();
            try {
                systemLogin.logOut();
            } catch (IOException ex) {
                System.out.println("systemLogin.logOut() 예외 발생");
            }
            LoginGUI login = new LoginGUI();
            login.setDefaultCloseOperation(LoginGUI.EXIT_ON_CLOSE);
            login.pack();
            login.setLocationRelativeTo(null);
            login.setVisible(true);

            dispose();
        }
    }//GEN-LAST:event_jButtRogOutActionPerformed

>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtClassStudentList;
    private javax.swing.JButton jButtExit;
    private javax.swing.JButton jButtGradeInput;
    private javax.swing.JButton jButtPWChange;
<<<<<<< HEAD
    private javax.swing.JButton jButtRoll;
=======
    private javax.swing.JButton jButtRogOut;
    private javax.swing.JButton jButtRoll;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
>>>>>>> 973819ee6e6c4532a12a2cf02bb3527f415334b9
    // End of variables declaration//GEN-END:variables
}
